add Introduction, Authentication, Errors sections and Users endpoints
elasticio/api-docs pull request #487
Opened 2021-11-04 17:47 UTC by HannaTrotsenko

How it can looks like
![image](https://user-images.githubusercontent.com/28867440/140391939-8a514808-efcc-42f5-8ddf-749830de71bd.png)
![image](https://user-images.githubusercontent.com/28867440/140392037-39e39af3-9b06-476e-af57-2176b8299078.png)
![image](https://user-images.githubusercontent.com/28867440/140392108-497eb916-b6ff-42a5-b135-2be6d5fa2496.png)

2021-11-10 12:40 UTC, PaulAnnekov requested changes
The formatting is inconsistent. You can use VS Code autoformat feature.

2021-11-10 12:40 UTC, PaulAnnekov commented on docs/openapi-spec/elasticio_RESTAPI.yaml
> +            description: Amount of items per page. Default 50
Defaults are written inside `schema`

2021-11-10 12:40 UTC, PaulAnnekov commented on docs/openapi-spec/elasticio_RESTAPI.yaml
> +            required: false
It's false by default. Let's use `required` only with `true`

2021-11-10 12:40 UTC, PaulAnnekov commented on docs/openapi-spec/elasticio_RESTAPI.yaml
> +            name: page[number]
I think paging-related params can be moved into `components` and reused in lot of places

2021-11-10 12:40 UTC, PaulAnnekov commented on docs/openapi-spec/elasticio_RESTAPI.yaml
> +        | attributes.password | yes | User's password. Password should be at least 8 characters long and include letters, numbers and special symbols.|
useless

2021-11-10 12:40 UTC, PaulAnnekov commented on docs/openapi-spec/elasticio_RESTAPI.yaml
> +        '401':
maybe all errors are better to make fully references to `components`

2021-11-10 12:54 UTC, HannaTrotsenko commented on docs/openapi-spec/elasticio_RESTAPI.yaml
> +    Welcome to the {{product_name}} [REST](http://en.wikipedia.org/wiki/Representational_State_Transfer) API documentation v2. It adheres to the [JSON API](http://jsonapi.org) specifications:
{{product_name}} - it's copy-paste from our markdown and means an eio variable, now swagger. I left it with {{}} to understand that we have to try find some way to make it configurable per api_url in tenant. Is it make sence?

2021-11-10 13:51 UTC, HannaTrotsenko commented on docs/openapi-spec/elasticio_RESTAPI.yaml
> +                $ref: '#/components/schemas/myUserOut'
actually we have a different shemas for each endpoint (for body, for responses by ID, for responses as array data). do you thik we really need to inline all of them in the `paths` section?

2021-11-10 13:51 UTC, HannaTrotsenko commented on docs/openapi-spec/elasticio_RESTAPI.yaml
> +      security:
I use this in the root
```
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
```
and according to docs apply it for a each request https://swagger.io/docs/specification/authentication/
Coorect if I understand documentation wrong

2021-11-10 13:51 UTC, HannaTrotsenko commented on docs/openapi-spec/elasticio_RESTAPI.yaml
> +        | attributes.password | yes | User's password. Password should be at least 8 characters long and include letters, numbers and special symbols.|
can't find the place where to post the description for body parameters. need hepl from your side

2021-11-10 13:51 UTC, HannaTrotsenko commented on docs/openapi-spec/elasticio_RESTAPI.yaml
> +        '401':
the shcmas are already in componentns, but all 403 differen for each endpoint because we have different permissions and each error text is different. So I think it's better to leave description as is

2021-11-10 15:48 UTC, PaulAnnekov commented on docs/openapi-spec/elasticio_RESTAPI.yaml
> +    Welcome to the {{product_name}} [REST](http://en.wikipedia.org/wiki/Representational_State_Transfer) API documentation v2. It adheres to the [JSON API](http://jsonapi.org) specifications:
Swagger by default doesn't have an ability to replace something in descriptions with variables. So we need to write this feature ourselves. I prefer to not write the code, so it's better to leave descriptions w/o dynamic parts. `title` will be a place where dynamic product name is mentioned.

2021-11-10 15:49 UTC, PaulAnnekov commented on docs/openapi-spec/elasticio_RESTAPI.yaml
> +      description: |
I mean remove `description` completely. What additional information does it provide that is not provided by other directives? Nothing.

2021-11-10 15:51 UTC, PaulAnnekov commented on docs/openapi-spec/elasticio_RESTAPI.yaml
> +                $ref: '#/components/schemas/myUserOut'
🤔 maybe it makes sense... Let's make `components` be our single source of all schemas.

2021-11-10 15:53 UTC, PaulAnnekov commented on docs/openapi-spec/elasticio_RESTAPI.yaml
> +      security:
https://swagger.io/specification/#openapi-object
![image](https://user-images.githubusercontent.com/1203892/141146553-adf1e891-3f92-441c-98f1-342153d76f48.png)

2021-11-10 16:01 UTC, HannaTrotsenko commented on docs/openapi-spec/elasticio_RESTAPI.yaml
> +      description: |
Ah, understand. I think maybe it's better to discuss with Tigran ? @khanzadyan  do we need so detalised explanation for request as we have now (because this description is a simple copy-paste from existing api-docs)

2021-11-10 16:02 UTC, PaulAnnekov commented on docs/openapi-spec/elasticio_RESTAPI.yaml
> +          This request is authorized for users with the `tenants.user.list_all` permission.
Something like:
```
security:
  - basicAuth:
    - tenants.user.list_all
```

But it will work only for renderers which support openapi 3.1. Should be supported by https://www.npmjs.com/package/swagger-ui. Need to check how it will look like in UI.

2021-11-10 16:04 UTC, PaulAnnekov commented on docs/openapi-spec/elasticio_RESTAPI.yaml
> +        | attributes.password | yes | User's password. Password should be at least 8 characters long and include letters, numbers and special symbols.|
https://swagger.io/specification/#operation-object
![image](https://user-images.githubusercontent.com/1203892/141148595-88f9f527-31c2-4c2c-9014-e10dd379f5f6.png)

2021-11-10 16:07 UTC, PaulAnnekov commented on docs/openapi-spec/elasticio_RESTAPI.yaml
> +        '401':
I don't think we should be so verbose to define exact error message for each endpoint. It's a lot of time. Let's start from generic schemas and then maybe in future we will add description per endpoint.

2021-11-10 16:10 UTC, PaulAnnekov commented on docs/openapi-spec/elasticio_RESTAPI.yaml
> +      description: |
Previously we didn't have such reach UI which is rendered by Swagger just from our directives. Now we have it and this descriptions repeats what is already rendered by Swagger.

2021-11-12 14:54 UTC, HannaTrotsenko commented on docs/openapi-spec/elasticio_RESTAPI.yaml
> +      security:
Removed from path and put in the root

2021-11-12 14:56 UTC, HannaTrotsenko commented on docs/openapi-spec/elasticio_RESTAPI.yaml
> +            name: page[number]
https://stackoverflow.com/questions/27005105/swagger-openapi-use-ref-to-pass-a-reusable-defined-parameter/54286746#54286746

2021-11-30 16:45 UTC, HannaTrotsenko commented
all comments are fixed but we will change the files structure and will give the new PR when all docs will be finished

2021-11-30 16:45 UTC, closed without merging